{% set version = "0.30.0" %}

package:
  name: python-packit
  version: '{{ version }}'

source:
  url: https://files.pythonhosted.org/packages/source/p/packit/packit-{{ version }}.tar.gz
  sha256: '0dc7efbde8d460985e2d8f538ac6171471ed4ad4ed98959f78e3758d348724ce'

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - wheel >=0.24
    - pbr >=4.0,<5.6.0
    - glob2 >=0.4.1
    - packaging >=16.8

  run:
    - python
    - wheel >=0.24
    - pbr >=4.0,<5.6.0
    - glob2 >=0.4.1
    - packaging >=16.8

test:
  imports:
    - packit

about:
  home: https://pypi.org/project/packit
  license: Public Domain
  summary: 'PacKit is wrapper around pbr though it only uses it for interaction with setuptools/distutils through simplified interface.'
  license_file: LICENSE
  license_family: Public Domain

extra:
  recipe-maintainers:
    - r78v10a07
