travis:
  secure:
    BINSTAR_TOKEN: mKatCJN6UtpDjWuT/cR2ogZ4nboFt2OKnNRJXkLerK24YfCUBxGc1TjWBP6AhN/bbiexLBrZYPHJlw8VplsxDWvFmtNP6QYu00LSyD1bISB6lv39h/6LTHQW+Y4wjp1asAaOy6/WE5ByYdqZjv8EPPD2bxgD4ExO0V5Zz1GBn1kHRq3B44AUENJHDec/s83GkUfhioMqmKpf5x40FE40BgR2NMyLEvy+2Y1ONMWKsGd7rJO5tnxt2T2+vrc3MP/fb+1IH9QjnSRp+MkYVsYugGZ3/I83WqCHJ43H/69P+gEqsayLTvB/iLno59VRJxHATlxyIZX9m5mPsq7EAOdQUAKXvcBGLavbX0Zzk8/svSt3qneV3S1CloW/F+On9y6O3MjZ2qWneZtWU7w0ODQ6xE5AjZeCdPDCpX6/6rwp81T1IbH3G77HCXqjNnb0639FFtSLKfSwZmyFNic4DKCKNKSwPG7igX2f9o7YGqTY7a1x31kvZGtqoWKs98OeCstyD75TVYTYvaDJRYuPC4EwpdYDcsNg/z44BdKs9oj3xzEUIZ7bd5fJ2tCBDEd0OuOWLqE2VCtMaGXdNzj7FbVVHeh570pYYhJ3xRpdz3VX5FqDe9P8v74QM3Z0ds/PdZr27ZNQCES0Bjw+erZyDaK0S3RhuqGQrJ3dMeY64xhtVmA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
